plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    alias(libs.plugins.roborazzi)
    alias(libs.plugins.secrets)
}

android {
    namespace 'com.stashly.stashly'
    compileSdk 36

    defaultConfig {
        applicationId "com.stashly.stashly"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            crunchPngs false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            // Default signingConfig is signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig true
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

secrets {
    propertiesFileName = ".env"
    defaultPropertiesFileName = ".env.example"
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.13.0')
    implementation 'com.google.firebase:firebase-analytics'

   
    implementation libs.firebase.auth
    implementation libs.firebase.firestore
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.room.runtime
    implementation libs.converter.moshi
    implementation libs.logging.interceptor
    implementation libs.moshi
    implementation libs.okhttp
    implementation libs.retrofit
    
    testImplementation libs.androidx.core
    testImplementation libs.androidx.junit
    testImplementation libs.junit
    testImplementation libs.robolectric
    testImplementation libs.roborazzi
    testImplementation libs.roborazzi.junit.rule
    
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.runner
    
    annotationProcessor libs.androidx.room.compiler
}
